### ISSUE TITLE
build error vs 2015 多字符集

### ISSUE THREAD

**Issue by 678uhb** [SOUI2/soui#16]
src\control\SSpinButton.cpp(234): error C2664: “int _wtoi(const wchar_t *)”: 无法将参数 1 从“SOUI::SStringT”转换为“const wchar_t *”

src\control\STileView.cpp(709): error C2664: “SOUI::STileViewItemLocator::STileViewItemLocator(SOUI::STileViewItemLocator &&)”: 无法将参数 1 从“const pugi::char_t *”转换为“int”

2>src\helper\STileViewItemLocator.cpp(19): error C2664: “SOUI::SLayoutSize SOUI::SLayoutSize::fromString(const SOUI::SStringW &)”: 无法将参数 1 从“LPCTSTR”转换为“const SOUI::SStringW &”

----------------------------------------------------------------------------------------
1>------ 已启动生成: 项目: utilities, 配置: Debug Win32 ------
1>  utilities.vcxproj -> D:\git\soui\utilities\..\bin\utilitiesd.dll
1>  utilities.vcxproj -> ..\bin\utilitiesd.pdb (Full PDB)
2>------ 已启动生成: 项目: soui, 配置: Debug Win32 ------
2>  souistd.h.cpp
2>  Accelerator.cpp
2>  AppDir.cpp
2>  DragWnd.cpp
2>  EventSet.cpp
2>  FocusManager.cpp
2>  MemDC.cpp
2>  MenuWndHook.cpp
2>  NotifyCenter.cpp
2>  SActiveX.cpp
2>  SApp.cpp
2>  SAxContainer.cpp
2>  SBStr.cpp
2>  SCalendar.cpp
2>  SCaption.cpp
2>  SCmnCtrl.cpp
2>  SComboBase.cpp
2>  SComboBox.cpp
2>  SComboView.cpp
2>  SDateTimePicker.cpp
2>  SDpiAwareFont.cpp
2>  SDropDown.cpp
2>  SDropTargetDispatcher.cpp
2>  SFontPool.cpp
2>  SGridLayout.cpp
2>  SHeaderCtrl.cpp
2>src\control\SHeaderCtrl.cpp(42): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
2>src\control\SHeaderCtrl.cpp(279): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
2>  SHostDialog.cpp
2>  SHotKeyCtrl.cpp
2>  SInterpolatorImpl.cpp
2>  SItemPanel.cpp
2>  SLayoutSize.cpp
2>  SLinearLayout.cpp
2>  SListCtrl.cpp
2>  SListView.cpp
2>  SListViewItemLocator.cpp
2>  SListbox.cpp
2>  SMcListView.cpp
2>  SMenu.cpp
2>  SMenuBar.cpp
2>  SMessageBox.cpp
2>d:\git\soui\soui\include\core\SWnd.h(525): warning C4477: “_snprintf_s”: 格式字符串“%s”需要类型“char *”的参数，但可变参数 1 拥有了类型“LPCWSTR” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%ls” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%lls” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%Ls” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%ws” (编译源文件 src\control\SMessageBox.cpp)
2>  src\control\SMessageBox.cpp(163): note: 参见对正在编译的函数 模板 实例化“T *SOUI::SWindow::FindChildByName2<SOUI::STabCtrl>(LPCWSTR,int)”的引用
2>          with
2>          [
2>              T=SOUI::STabCtrl
2>          ]
2>d:\git\soui\soui\include\core\SWnd.h(525): warning C4477: “_snprintf_s”: 格式字符串“%s”需要类型“char *”的参数，但可变参数 2 拥有了类型“LPCWSTR” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%ls” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%lls” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%Ls” (编译源文件 src\control\SMessageBox.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(525): note: 请考虑在格式字符串中使用“%ws” (编译源文件 src\control\SMessageBox.cpp)
2>  SMsgLoop.cpp
2>  SNamedValue.cpp
2>  SObjDefAttr.cpp
2>  SObjectFactory.cpp
2>  SPanel.cpp
2>  SRealWnd.cpp
2>  SResProvider.cpp
2>  SResProviderMgr.cpp
2>  SRichEdit.cpp
2>  SScriptTimer.cpp
2>  SScrollbar.cpp
2>  SSkin.cpp
2>  SSkinPool.cpp
2>  SSliderBar.cpp
2>  SSpinButton.cpp
2>  SSpinButtonCtrl.cpp
2>src\control\SSpinButton.cpp(234): error C2664: “int _wtoi(const wchar_t *)”: 无法将参数 1 从“SOUI::SStringT”转换为“const wchar_t *”
2>  src\control\SSpinButton.cpp(234): note: 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
2>  SSplitWnd.cpp
2>  SStylePool.cpp
2>  STabCtrl.cpp
2>  STileView.cpp
2>  STileViewItemLocator.cpp
2>src\control\STileView.cpp(709): error C2664: “SOUI::STileViewItemLocator::STileViewItemLocator(SOUI::STileViewItemLocator &&)”: 无法将参数 1 从“const pugi::char_t *”转换为“int”
2>  src\control\STileView.cpp(709): note: 没有使该转换得以执行的上下文
2>src\helper\STileViewItemLocator.cpp(14): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
2>src\helper\STileViewItemLocator.cpp(19): error C2664: “SOUI::SLayoutSize SOUI::SLayoutSize::fromString(const SOUI::SStringW &)”: 无法将参数 1 从“LPCTSTR”转换为“const SOUI::SStringW &”
2>  src\helper\STileViewItemLocator.cpp(19): note: 原因如下: 无法从“LPCTSTR”转换为“const SOUI::SStringW”
2>  src\helper\STileViewItemLocator.cpp(19): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
2>src\helper\STileViewItemLocator.cpp(20): error C2664: “SOUI::SLayoutSize SOUI::SLayoutSize::fromString(const SOUI::SStringW &)”: 无法将参数 1 从“LPCTSTR”转换为“const SOUI::SStringW &”
2>  src\helper\STileViewItemLocator.cpp(20): note: 原因如下: 无法从“LPCTSTR”转换为“const SOUI::SStringW”
2>  src\helper\STileViewItemLocator.cpp(20): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
2>src\helper\STileViewItemLocator.cpp(102): error C2664: “SOUI::SLayoutSize SOUI::SLayoutSize::fromString(const SOUI::SStringW &)”: 无法将参数 1 从“LPCTSTR”转换为“const SOUI::SStringW &”
2>  src\helper\STileViewItemLocator.cpp(102): note: 原因如下: 无法从“LPCTSTR”转换为“const SOUI::SStringW”
2>  src\helper\STileViewItemLocator.cpp(102): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
2>src\helper\STileViewItemLocator.cpp(109): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
2>  STimerEx.cpp
2>  STreeCtrl.cpp
2>  STreeView.cpp
2>  SUiDef.cpp
2>  SUpdateLayeredWindow.cpp
2>  SWindowMgr.cpp
2>  SimpleWnd.cpp
2>  SouiLayout.cpp
2>  Swnd.cpp
2>  SwndContainerImpl.cpp
2>  SwndFinder.cpp
2>  SwndStyle.cpp
2>  scaret.cpp
2>  sdibhelper.cpp
2>  shostwnd.cpp
2>  slog.cpp
2>  smatrix.cpp
2>  smenuex.cpp
2>  stooltip.cpp
2>d:\git\soui\soui\include\core\SWnd.h(488): warning C4477: “_snprintf_s”: 格式字符串“%s”需要类型“char *”的参数，但可变参数 1 拥有了类型“LPCWSTR” (编译源文件 src\helper\smenuex.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(488): note: 请考虑在格式字符串中使用“%ls” (编译源文件 src\helper\smenuex.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(488): note: 请考虑在格式字符串中使用“%lls” (编译源文件 src\helper\smenuex.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(488): note: 请考虑在格式字符串中使用“%Ls” (编译源文件 src\helper\smenuex.cpp)
2>  d:\git\soui\soui\include\core\SWnd.h(488): note: 请考虑在格式字符串中使用“%ws” (编译源文件 src\helper\smenuex.cpp)
2>  src\helper\smenuex.cpp(600): note: 参见对正在编译的函数 模板 实例化“T *SOUI::SWindow::FindChildByID2<SOUI::SMenuExItem>(int,int)”的引用
2>          with
2>          [
2>              T=SOUI::SMenuExItem
2>          ]
========== 生成: 成功 1 个，失败 1 个，最新 1 个，跳过 0 个 ==========

**Comment by setoutsoft** [comment]
试试master最新版本。多字节不定期检查。国内的朋友可以在QQ群里提。
