### ISSUE TITLE
小bug修改以及建议

### ISSUE THREAD

**Issue by chaijh** [SOUI2/soui#19]
SOUI 非常不错，比较实用！

最近在做高 DPI 适配，SOUI也在持续改进中，效果还可以，发现几个小问题：
1. STileView 不能适配高DPI
修改：
void STileView::SetItemLocator 中加入
m_tvItemLocator->SetScale(GetScale());

2. SSplitPane 不能适配高DPI
修改：
SSplitPane 使用 SLayoutSize
		ATTR_LAYOUTSIZE(L"idealSize", m_nSizeIdeal, FALSE)
		ATTR_LAYOUTSIZE(L"minSize", m_nSizeMin, FALSE)
		ATTR_LAYOUTSIZE(L"maxSize", m_nSizeMax,FALSE)

3. SDpiHandler
ProcessWindowMessage 中处理 WM_INITDIALOG 消息处，窗口size变化要基于原size居中，
HandleScaleChange(nScale, &rc);
之前加入：
CPoint ntl = rc.CenterPoint();
ntl.Offset(-sz.cx / 2, -sz.cy / 2);
rc = CRect(ntl, sz);
否则原来居中显示的对话框会不居中了。

还有个问题就是为什么每个窗口要有单独的 m_nScale？整个全局弄一个不就好了？理论上一个程序内部应该只需要一种 DPI 不是吗？现在这样很容易造成一个程序内部 DPI 不统一，仅供参考。

最后谢谢作者，希望SOUI越来越好！

**Comment by setoutsoft** [comment]
SDpiHandler你这样处理更好。两个控件不支持dpi可能是因为以前没有用到。
每个窗口都保留一个m_nScale变量，主要是为了方便在控件内获取scale。由于不同窗口可能有不同的scale（比如在不同显示器上），所以使用全局的nScale是不合适的。
如果把nScale只放到hostwnd里，在控件里获取scale会很麻烦，不如每个控件持有一个简单快速。算是空间换时间。
你修改好的代码，可以发起pull request，我会及时处理。
