### ISSUE TITLE
非利益相关，想问下航信开票3.0是由于什么原因被加入了黑名单

### ISSUE THREAD

**Issue by Adam-Jin** [SOUI2/soui#25]
你好，我这边有一个自动化航信开票软件的需求，使用MSAA或者UIA。在新的航信3.0开票软件上，内部的控件均没有可访问性，在安装目录也没有看到soui相关模块。同时我看到组件有对acc的支持，想问下是否是他们的开发人员对可访问性等做了改动

**Comment by setoutsoft** [comment]
加黑名单是因为没有按照SOUI的开源协议在安装包中带上SOUI的license。
SOUI内核支持ACC, 不过不同控件的实现并不完整。

**Comment by setoutsoft** [comment]
ACC功能默认不开启。所以一般软件里用ACC应该是不行的。

**Comment by Adam-Jin** [comment]
了解，谢谢
