### ISSUE TITLE
No support for the open source MinGW64 compiler?

### ISSUE THREAD

**Issue by tn1997tn** [SOUI2/soui#34]
I was able to have cmake configured and generated the ninja build script. But when actually started the build, it failed with:

```
[1/1025] Generating C unity source third-part/zlib/cotire/zlib_C_unity.c
[2/1025] Generating C prefix source third-part/zlib/cotire/zlib_C_prefix.c
[3/1025] Generating C prefix header third-part/zlib/cotire/zlib_C_prefix.h
[4/1025] Building C precompiled header third-part/zlib/cotire/zlib_C_prefix.h.gch
[5/1025] Building C object third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj
FAILED: third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj
C:\msys64\mingw64\bin\cc.exe -DUNICODE -D_CRT_SECURE_NO_WARNINGS -D_UNICODE  /MP /wd4100 /wd4189 /wd4996 -Winvalid-pch -include C:/msys64/home/Administrator/soui/build/third-part/zlib/cotire/zlib_C_prefix.h -MD -MT third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj -MF third-part\zlib\CMakeFiles\zlib.dir\adler32.c.obj.d -o third-part/zlib/CMakeFiles/zlib.dir/adler32.c.obj -c C:/msys64/home/Administrator/soui/third-part/zlib/adler32.c
cc.exe: warning: /MP: linker input file unused because linking not done
cc.exe: error: /MP: linker input file not found: No such file or directory
cc.exe: warning: /wd4100: linker input file unused because linking not done
cc.exe: error: /wd4100: linker input file not found: No such file or directory
cc.exe: warning: /wd4189: linker input file unused because linking not done
cc.exe: error: /wd4189: linker input file not found: No such file or directory
cc.exe: warning: /wd4996: linker input file unused because linking not done
cc.exe: error: /wd4996: linker input file not found: No such file or directory
ninja: build stopped: subcommand failed.
```

Noticed the build options are all MSVC specific?

**Comment by tn1997tn** [comment]
This is the faulty lines on `global.cmake`:

https://github.com/SOUI2/soui/blob/master/__cmake/global.cmake#L35

Wrap them in `if (MSVC)` and `endif()` then I could continue to build. In the process, I discovered this library use so much MSVC specific stuffs, so it's practically impossible to support MinGW64 without a big refactoring of code.

**Comment by setoutsoft** [comment]
the latest version of soui is soui4. (https://github.com/soui4/soui)
Animation, Dpi aware, multiple language were done in soui4 and most of features that provided by msvc only were removed.

**Comment by setoutsoft** [comment]
I think soui3 will share the same problem with soui2. soui4 will be better.

**Comment by hgntn** [comment]
MinGW-w64 doesn't support MFC or ATL. If your library uses any of them (I think very likely) then it's no hope. MSVC specific extensions like `__pragma` and `__super` will also cause problems as MinGW-w64 doesn't support them. On MinGW-w64, people use Win32++ as an alternative: https://win32-framework.sourceforge.net/
