### ISSUE TITLE
(测试issues)qqlogin的imre使用skia渲染的时候,图片显示有问题

### ISSUE THREAD

**Issue by cjl3230** [SOUI2/soui#7]
**git版本号:**
b5394fbd2b966ba639d9a18ee31ac6fcb0e16116
**问题描述:**
qqlogin的imre使用skia渲染的时候,图片显示有问题
如图所示
![issue_bug1](https://cloud.githubusercontent.com/assets/2327445/26823224/7ab6db58-4adf-11e7-89ec-a0c3395df7ab.jpg)
**猜测问题原因:**
SAntialiasSkin类可能存在问题导致和skia不兼容

**Comment by setoutsoft** [comment]
这是已知问题，和SOUI内核没有关系。
